name: "test itself"
on:
  push:
    branches:
      - 'test'
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
     - name: Check out repository
       uses: actions/checkout@v2
     - uses: ./
       with:
          extra: 345
